== Le développement professionnel continu en Java

=== O'Reilly Media

|==========================================================================================
| Andrew Lee Rubinger | +alr@continuousdev.org+ | http://twitter.com/ALRubinger['@ALRubinger']
| Aslak Knutsen | +aslak@continuousdev.org+ | http://twitter.com/aslakknutsen['@aslakknutsen']
|==========================================================================================

Le dépôt officiel Git contenant le livre et le code source de l'application exemple pour "Le développement professionnel continu en Java" par Andrew Lee Rubinger et Aslak Knutsen, publié par O'Reilly Media, est hébergé par nos amis de http://www.github.com[GitHub] à https://github.com/arquillian/continuous-enterprise-development[https://github.com/arquillian/continuous-enterprise-development].  Le site accompagnant ce livre se trouve à http://continuousdev.org[http://continuousdev.org] et le canal Twitter officiel est http://twitter.com/ContinuousDev[@ContinuousDev].  Les auteurs peuvent être contactés via authors@continuousdev.org.

Tout le contenu de ce dépôt est sous license http://creativecommons.org/licenses/by-sa/2.0/['Creative Commons Attribution-ShareAlike 2.0 Generic'] et nous invitons la communauté à contribuer via des demandes d'évolution, des corrections d'erreurs typographiques et des améliorations via notre https://github.com/arquillian/continuous-enterprise-development/issues[GitHub Issue Tracker].

La distribution officielle de ce livre sera disponible aux formats papier et électronique via http://shop.oreilly.com/product/0636920025368.do[O'Reilly] ou d'autres détaillants tiers en Septembre 2013.  La version Early Access Release est disponible à la vente depuis l'automne 2012.

La version papier du livre et les exemples correspondront au tag +1.0.0+ du dépôt Git, le développement se poursuivra dans la branche +master+ pour les corrections et l'ajout de nouveaux contenus tels que chapitres et cas d'utilisation.  La communauté est encouragée à suggérer ou demander de nouveaux sujets à couvrir.

L'application exemple qui accompagne les cas d'utilisation traités dans le livre s'appelle GeekSeek et est disponible publiquement à http://geekseek.continuousdev.org[http://geekseek.continuousdev.org].  Le code source se trouve dans ce même dépôt dans le répertoire +code/application+ et les instructions pour le construire, le tester et l'exécuter localement sont détaillées dans le https://github.com/arquillian/continuous-enterprise-development/blob/master/Chapter04-RequirementsAndExampleApplication.asciidoc[Chapitre 4].

Nous encourageons vos contributions et espérons que vous trouverez le contenu intéressant et enrichissant pour votre travail et votre carrière dans le monde du développement d'entreprise testable.
